name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y expect
  

    - name: Install e2e CLI
      run: |
        pip install e2e-cli
    
    - name: Check api and auth token
      run: |
        echo "${{ secrets.E2E_API_KEY }}"
        echo "${{ secrets.E2E_AUTH_TOKEN }}"

    - name: Execute Interactive Command
      env:
        APIKEY: ${{ secrets.E2E_API_KEY }}
        AUTHTOKEN: ${{ secrets.E2E_AUTH_TOKEN }}
      run: |
        echo "Starting Interactive Command"
        # Replace 'your_command_let' with the actual command that requires input
        # You may need to adjust this command to match your specific use case
        # expect -c '
        #     spawn e2e_cli alias add
        #     expect "Enter your api key:" 
        #     send "51f04644-95c2-4836-a550-61cab7013c73\r"
        #     expect "Enter your auth token:"
        #     send "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGSjg2R2NGM2pUYk5MT2NvNE52WmtVQ0lVbWZZQ3FvcXRPUWVNZmJoTmxFIn0.eyJleHAiOjE3MzU3MDQ4NDcsImlhdCI6MTcwNDE2ODg0NywianRpIjoiNjE3Nzg2ZTAtZDg0Yy00NjFhLTg4ZjctY2QzYjk4MDFiZmNiIiwiaXNzIjoiaHR0cDovL2dhdGV3YXkuZTJlbmV0d29ya3MuY29tL2F1dGgvcmVhbG1zL2FwaW1hbiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI2ODM3YTA1YS01M2EyLTQwOGQtYjViMS1mZTI4YjJhNmQxMjAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhcGltYW51aSIsInNlc3Npb25fc3RhdGUiOiJiMDAzM2JlYS1mY2RhLTQ2NDAtODRhZC00MDc0NDdjZmJhM2MiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImFwaXVzZXIiLCJkZWZhdWx0LXJvbGVzLWFwaW1hbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImIwMDMzYmVhLWZjZGEtNDY0MC04NGFkLTQwNzQ0N2NmYmEzYyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IlRhcnVuIFNpbmdoIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidGFydW4uc2luZ2hAZTJlbmV0d29ya3MuY29tIiwiZ2l2ZW5fbmFtZSI6IlRhcnVuIiwiZmFtaWx5X25hbWUiOiJTaW5naCIsImVtYWlsIjoidGFydW4uc2luZ2hAZTJlbmV0d29ya3MuY29tIn0.hWH_2D8-tbBDxo7aOj08agHmkFduTECWsuHB852xBx9GES94pO73O7uMEa_vcOCEH_RRbs9124IiwEJvwZNgW0x9H7-6q2Pjip2fFj1kvXra1Ny4Lc_bHsIJxl_JWncZJlcfRSNQX15Bff_mFN8xkd7Kcys0Cr91s9Q53YKPNh4\r"
        #     expect "Input name of alias you want to add :"
        #     send "e2ecreds\r"
        #     interact'
        expect -c '
            spawn e2e_cli alias add
            expect "Enter your api key:" 
            send "51f04644-95c2-4836-a550-61cab7013c73\r"
            expect "Enter your auth token:"
            send "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGSjg2R2NGM2pUYk5MT2NvNE52WmtVQ0lVbWZZQ3FvcXRPUWVNZmJoTmxFIn0.eyJleHAiOjE3MzU3MDQ4NDcsImlhdCI6MTcwNDE2ODg0NywianRpIjoiNjE3Nzg2ZTAtZDg0Yy00NjFhLTg4ZjctY2QzYjk4MDFiZmNiIiwiaXNzIjoiaHR0cDovL2dhdGV3YXkuZTJlbmV0d29ya3MuY29tL2F1dGgvcmVhbG1zL2FwaW1hbiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI2ODM3YTA1YS01M2EyLTQwOGQtYjViMS1mZTI4YjJhNmQxMjAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhcGltYW51aSIsInNlc3Npb25fc3RhdGUiOiJiMDAzM2JlYS1mY2RhLTQ2NDAtODRhZC00MDc0NDdjZmJhM2MiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImFwaXVzZXIiLCJkZWZhdWx0LXJvbGVzLWFwaW1hbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImIwMDMzYmVhLWZjZGEtNDY0MC04NGFkLTQwNzQ0N2NmYmEzYyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IlRhcnVuIFNpbmdoIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidGFydW4uc2luZ2hAZTJlbmV0d29ya3MuY29tIiwiZ2l2ZW5fbmFtZSI6IlRhcnVuIiwiZmFtaWx5X25hbWUiOiJTaW5naCIsImVtYWlsIjoidGFydW4uc2luZ2hAZTJlbmV0d29ya3MuY29tIn0.hWH_2D8-tbBDxo7aOj08agHmkFduTECWsuHB852xBx9GES94pO73O7uMEa_vcOCEH_RRbs9124IiwEJvwZNgW0x9H7-6q2Pjip2fFj1kvXra1Ny4Lc_bHsIJxl_JWncZJlcfRSNQX15Bff_mFN8xkd7Kcys0Cr91s9Q53YKPNh4\r"
            expect "Input name of alias you want to add :"
            send "e2ecreds\r"
            expect eof
            exit [wait]
        '


    - name: Default Alias Set
      run: |
        echo "Starting Interactive Command alias"
        # Replace 'your_command_let' with the actual command that requires input
        # You may need to adjust this command to match your specific use case
        expect -c '
            spawn e2e_cli alias set
            expect "Enter name of the alias you want to set as default :" 
            send "e2ecreds\r"
            expect "are you sure you want to proceed (y/n):"
            send "y\r"
            expect eof
            exit [wait]
        '
    # - name: Capture Faas list Output
    #   id: capture_output_faas_list
    #   run: |
    #     echo "Running a command..."
    #     # Replace 'your_command' with the actual command you want to run
    #     output=$(e2e_cli faas list)
    #     echo "::set-output name=command_output::$output"
    
    # - name: Capture Alias Output
    #   id: capture_output_alias_view
    #   run: |
    #     echo "Running a command..."
    #     # Replace 'your_command' with the actual command you want to run
    #     output=$(e2e_cli alias view)
    #     echo "::set-output name=command_output::$output"

    - name: Capture Faas list Output
      id: capture_output_faas_list
      run: |
        echo "Running a faas list command..."
        e2e_cli faas list
    
    - name: Capture Alias Output
      id: capture_output_alias_view
      run: |
        echo "Running a alias view command..."
        e2e_cli alias view
    
    # - name: List changed folders
    #   run: |
    #     export CHANGED_FOLDERS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
    #     | cut -d/ -f1 \
    #     | sort \
    #     | uniq)
    #     echo "::set-env name=CHANGED_FOLDERS::$CHANGED_FOLDERS"
      
    # - name: Loop over changed folders
    #   run: |
    #     for folder in $CHANGED_FOLDERS; do
    #       echo "Processing folder: $folder"
    #       e2e_cli faas deploy --name
    #     done

    - name: Deploy
      run: e2e_cli faas --name="e2e-function-py-f1" --lang="python" redeploy 
