name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python and pip
      run: |
        sudo apt update
        sudo apt install python3 python3-pip -y
        sudo apt-get install -y expect

    - name: Install e2e CLI
      run: |
        pip3 install e2e-cli
    
    - name: Execute Interactive Command
      env:
        APIKEY: ${{ secrets.E2E_API_KEY }}
        AUTHTOKEN: ${{ secrets.E2E_AUTH_TOKEN }}
      run: |
        echo "Starting Interactive Command"
        # Replace 'your_command_let' with the actual command that requires input
        # You may need to adjust this command to match your specific use case
        expect -c '
            spawn e2e_cli alias add
            expect "Enter your api key:" 
            send "$env(APIKEY)\r"
            expect "Enter your auth token:"
            send "$env(AUTHTOKEN)\r"
            expect "Input name of alias you want to add :"
            send "e2ecreds\r"
            interact'

    - name: Default Alias Set
      run: |
        echo "Starting Interactive Command"
        # Replace 'your_command_let' with the actual command that requires input
        # You may need to adjust this command to match your specific use case
        expect -c '
            spawn e2e_cli alias set
            expect "Enter name of the alias you want to set as default :" 
            send "e2ecreds\r"
            expect "are you sure you want to proceed (y/n):"
            send "y\r"
            interact'
    # - name: Capture Faas list Output
    #   id: capture_output_faas_list
    #   run: |
    #     echo "Running a command..."
    #     # Replace 'your_command' with the actual command you want to run
    #     output=$(e2e_cli faas list)
    #     echo "::set-output name=command_output::$output"
    
    # - name: Capture Alias Output
    #   id: capture_output_alias_view
    #   run: |
    #     echo "Running a command..."
    #     # Replace 'your_command' with the actual command you want to run
    #     output=$(e2e_cli alias view)
    #     echo "::set-output name=command_output::$output"

    - name: Capture Faas list Output
      id: capture_output_faas_list
      run: |
        echo "Running a faas list command..."
        e2e_cli faas list
    
    - name: Capture Alias Output
      id: capture_output_alias_view
      run: |
        echo "Running a alias view command..."
        e2e_cli alias view
    
    # - name: List changed folders
    #   run: |
    #     export CHANGED_FOLDERS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
    #     | cut -d/ -f1 \
    #     | sort \
    #     | uniq)
    #     echo "::set-env name=CHANGED_FOLDERS::$CHANGED_FOLDERS"
      
    # - name: Loop over changed folders
    #   run: |
    #     for folder in $CHANGED_FOLDERS; do
    #       echo "Processing folder: $folder"
    #       e2e_cli faas deploy --name
    #     done

    - name: Deploy
      run: e2e_cli faas --name="e2e-function-py-f1" --lang="python" redeploy 
